### ISSUE TITLE
BadMethodCallException on attempting to install plugin

### ISSUE THREAD

**Issue by emeehangsu** [omeka/plugin-ImageAnnotation#5]
I'm trying to install Image Annotation v 1.0.1 and I am receiving this error:

BadMethodCallException
Method named 'exec' does not exist or is not callable.

`exception 'BadMethodCallException' with message 'Method named 'exec' does not exist or is not callable.' in /home/meehangs/public_html/omeka/application/libraries/Omeka/Db.php:68
Stack trace:
#0 /home/meehangs/public_html/omeka/plugins/ImageAnnotation/plugin.php(52): Omeka_Db->__call('exec', Array)
#1 /home/meehangs/public_html/omeka/plugins/ImageAnnotation/plugin.php(52): Omeka_Db->exec('CREATE TABLE IF...')
#2 [internal function]: image_annotation_install(Array)
#3 /home/meehangs/public_html/omeka/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func('image_annotatio...', Array)
#4 /home/meehangs/public_html/omeka/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#5 /home/meehangs/public_html/omeka/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#6 /home/meehangs/public_html/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#7 /home/meehangs/public_html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#8 /home/meehangs/public_html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /home/meehangs/public_html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#10 /home/meehangs/public_html/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#11 /home/meehangs/public_html/omeka/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#12 /home/meehangs/public_html/omeka/admin/index.php(28): Omeka_Application->run()
#13 {main}`

**Comment by patrickmj** [comment]
Some web servers are configured to not allow using the `exec` function, so the first thing will be to check with your hosting company or sysadmin to see if that is the cause of the problem.

**Comment by patrickmj** [comment]
I checked around a bit, and it seems like you might have found a very old version of the plugin, that isn't compatible with Omeka 2

**Comment by emeehangsu** [comment]
Good call on the version.  My problem was with the legacy version.  Thanks for the help!
